### ISSUE TITLE
Problem with dll versions (Unity.Wcf and Unity.Abstractions)

### ISSUE THREAD

**Issue by aracurd** [unitycontainer/wcf#4]
I'm trying to use Prism with Unity.Wcf. Problem that latest version of Unity.Wcf (5.9.0) needs UnityContainer >= 5.9.0. UnityContainer depends on Unity.Abstractions >= 4.0.0.
Latest version of Prism need UnityContainer 5.8.1 + Unity.Abstractions >= 3.3.1.

I try to use previous version Unity.Wcf (4.0) depends on Unity.Abstractions >= 2.0.0.  Unity.Wcf (4.0) can't work with Unity.Abstractions >= 3.3.1? So how to solve this problem?

Wcf result  > Could not load file or assembly 'Unity.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by ENikS** [comment]
You can ask Prism team to update Unity adapter to use the latest. There is no other way around it.

**Comment by aracurd** [comment]
> You can ask Prism team to update Unity adapter to use the latest. There is no other way around it.

It's the same if i ask you to update Unity.Wcf (4.0) to support Unity.Abstractions 3.3.1. I just don't understand why you write in dependency Unity.Abstractions >= 2.0.0 when you don't support version 3.3.1

**Comment by viceice** [comment]
@aracurd Did you try assembly binding redirects?

**Comment by aracurd** [comment]
> @aracurd Did you try assembly binding redirects?

In Web.config?

**Comment by viceice** [comment]
> > @aracurd Did you try assembly binding redirects?
> 
> In Web.config?

Yes, it's possible there.

**Comment by aracurd** [comment]
@ViceIce - Never use this. Should be something like this:
`<dependentAssembly>
        <assemblyIdentity name="Unity.Abstractions" publicKeyToken="6d32ff45e0ccc69f" culture="neutral" />
        <bindingRedirect oldVersion="2.0.0.0" newVersion="3.3.1.0" />
      </dependentAssembly>`


```

**Comment by aracurd** [comment]
@ViceIce Thanks it's works

**Comment by pspattillo** [comment]
I have a similar and possibly related problem that binding redirects do not seem to correct involving latest Prism codebase requesting Unity.Abstractions 3.3.1.0. I went with latest versions of all software involved and checked dependencies. Specifically, I am using Prism.Core (says it works for .Net 4.5 which I'm using) and Prism.Unity and Prism.WPF. 

Specifically Unity.Bootstrapper (part of Prism.Unity at version 7.1.0.431) is trying to load Unity.Abstractions 3.3.1.0 when it is documented as working with Unity.Container > 5.8.11 (no mention of Unity.Abstractions). I used ILSpy and sure enough it references Unity.Abstractions 3.3.1.0.

It's almost kooks like Prism authors thought Unity.Abstractions was part of Unity.Container. I tried the following binding redirect and realize that I many need to contact them but am not certain of how to get their attention and had just stumbled onto this post.

Big thanks for whatever help you can offer, even if confirming that I should contact Prism authors

    <runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
            <dependentAssembly>
                <assemblyIdentity name="Unity.Container" publicKeyToken="489b6accfaf20ef0" culture="neutral" />
                <bindingRedirect oldVersion="0.0.0.0-5.10.3.0" newVersion="5.10.3.0" />
            </dependentAssembly>
            <dependentAssembly>
                <assemblyIdentity name="Unity.Abstractions" publicKeyToken="489b6accfaf20ef0" culture="neutral" />
                <bindingRedirect oldVersion="0.0.0.0-4.1.3.0" newVersion="4.1.3.0" />
            </dependentAssembly>
        </assemblyBinding>
    </runtime>

**Comment by ENikS** [comment]
Prism library only works with specific version of Unity. Unity can not be updated without updating Prism.

This is due to continuing breaking charges in Unity.

You need to address this with Prism team and ask them to update to the latest.
