### ISSUE TITLE
README is out of date

### ISSUE THREAD

**Issue by velsietis** [unitycontainer/wcf#5]
The README says to edit the WcfServiceFactory class that has been added to solution.  
After installing this via nuget the class is not added.
It looks like this has been removed (cref: cc9a6486)

**Comment by viceice** [comment]
I know, sorry.

**Comment by viceice** [comment]
You have to add this class manually and extend from [UnityServiceHostFactory](https://github.com/unitycontainer/wcf/blob/38d1377b4b2846d67673be73777f6088ec005b3a/src/Hosting/UnityServiceHostFactory.cs#L7)

**Comment by velsietis** [comment]
Thanks, that's what I'm trying.

**Comment by ENikS** [comment]
Can either one of you update the readme?

**Comment by viceice** [comment]
Yes, hopefully tomorrow.
